--------------------------------------------------------------------------------------------------------
-- Chapter 8 practice 1 for chapter 8 lesson 1,2
-- 1. Write a query to display the department name, city, the address, country name of all the
-- departments. Use a NATURAL JOIN to produce the results.
-- 2. Write a query to display the employee last name, department ID, job ID, job title for all
-- employees working in departments number (10,90,20), Use a NATURAL JOIN to
-- produce the results
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 8 practice 2 for chapter 8 lesson 3
-- 1. Write a query to display the department name, city, the address, country name of all the
-- departments. Use USING CLAUSE JOIN to produce the results.
-- 2. Write a query to display the employee last name, department ID, job ID, job title for all
-- employees working in departments number (10,90,20), Use USING CLAUSE JOIN to
-- produce the results.
-- 3. Write a query to display the country ID, country name, region name for all countries
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 8 practice 3 for chapter 8 lesson 4
-- 1. Write a query to display employee last name ,department ID, department Name, City for
-- all employees who work in London city.
-- Chapter 8 practice 4 for chapter 8 lesson 5
-- 1. Write a query to display employees ID, employees’ last names along with their manager
-- numbers and managers’ last names, Provide an appropriate column alias for all columns
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 8 practice 5 for chapter 8 lesson 7
-- 1. Write a query to display city name, country name for all locations, including locations
-- that don’t have countries and countries that don’t have any location
-- Chapter 8 practice 6 for chapter 8 lesson 8
-- 1. Write a query to display the output of cross join countries table with regions table 
--------------------------------------------------------------------------------------------------------