--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 1 for chapter 12 lesson 1,2
-- 1. Create a table called dept with two columns deptid with data type number(7), and
-- deptname with data type varchar2(50)
-- 2. Check the table structure using SQL developer and using describe command.
-- 3. Create a table called emp with four columns emp_id as number(8) ,last_name as
-- varchar2(50), hire_date as date default sysdate, dept_id as number(7)
-- 4. Check the table structure using SQL developer and using describe command.
-- 5. Insert a record in the emp table and don’t’ put a value for hire_date column, check the
-- insert record, what do you observe?
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 2 for chapter 12 lesson 3
-- 1. Create a table called student with four columns student_id number(9), full_name
-- varchar2(50), email varchar2(40) default ‘test@test.com’, registered_hours number(4),
-- define student_id, full_name columns as not null, registered_hours must be greater than 0
-- 2. Test the constraints by inserting sample records
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 3 for chapter 12 lesson 4
-- 1. Create a table called instructor with four columns inst_id number(9), inst_name
-- varchar2(50), email varchar2(40) default ‘test@test.edu’, faculty_name varchar2(40),
-- define inst_id as primary key, inst_name not null, email as unique key
-- 2. Test the constraints by inserting sample records
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 4 for chapter 5
-- 1. Create a table called dept_new with three columns dept_id with data type number(7),
-- and dept_name with data type varchar2(20), loc_id number(4), define dept_id as
-- primary key and dept_name as not null
-- 2. Create a table called emp_new with five columns emp_id with data type number(7),
-- emp_name as varchar2(40), email as varchar2(60), salary as number(5), dept_id as
-- number (7), define emp_id as primary key, dept_id as foreign key referenced dept_new
-- (dept_id), salary must be between 400 and 20000, email unique, emp_name not null
-- 3. Test the constraints by inserting sample records
-- 4. Create a table called emp_new2 with five columns emp_id with data type number(7),
-- emp_name as varchar2(40), email as varchar2(60), salary as number(5), dept_id as
-- number (7), define emp_id as primary key, dept_id as foreign key referenced dept_new
-- (dept_id) on delete cascade, salary must be between 400 and 20000, email unique,
-- emp_name not null
-- 5. Test the constraints by inserting sample records
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 5 for chapter 12 lesson 6
-- 1. Create a table called emp_copy using select * from table emp_new
-- 2. Check the structure of emp_copy table, check the constraints, what you noticed?
-- 3. Creat a table called dept_copy using select * from dept_new, name the columns as
-- department_id, department_name, location_id
-- 4. Check the structure of dept_copy table what you noticed?
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 6 for chapter 12 lesson 7
-- 1. Alter emp_copy and add new column called manager_id number(7)
-- 2. Alter table dept_copy change the size of the column department_name to varchar2(25)
-- 3. Alter table emp_copy drop the column manager_id
-- 4. Alter table dept_copy rename the column department_name to dept_name
-- 5. Change the table dept_copy to read only and try to insert a record, what you noticed?
-- 6. Change the table dept_copy to read write and try to insert a record
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 12 practice 7 for chapter 12 lesson 8
-- 1. Drop the following tables: emp_copy, dept_copy
-- 2. Drop the following tables: emp_new2, dept, student, instructor use purge keyword
--------------------------------------------------------------------------------------------------------
