--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 14 practice 1 for chapter 14 lesson 1,2
-- 1. Create a view called emp_vu40 based on the employee numbers, employee last
-- names with first name, and department numbers from the EMPLOYEES table where
-- department_id equal to 40. The heading for the employee name should be
-- FULL_NAME, save the create statement to a file named emp_vu40.sql
-- 2. View the structure of the view and confirm the view works
-- 3. Create a view called emp_vu_details that presents the employee number, employee full
-- name, salary, department name of all employees
-- 4. View the structure of the view and confirm the view works
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 14 practice 2 for chapter 14 lesson 3
-- 1. Modify the view called emp_vu40 and include column hire_date
-- 2. View the structure of the view and confirm the view works
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 14 practice 3 for chapter 14 lesson 4
-- 1. Create a view called emp_svu that presents the sum of all salaries per each department
-- 2. Try to do insert statement on emp_svu, what you observed?
-- 3. Create a view called emp_vu based employee name, email, salary from table emp_new
-- 4. Try to do insert statement on emp_vu, what you observed?
-- 5. Modify the view emp_vu and include emp_id in the view
-- 6. Try to do insert statement on emp_vu, what you observed?
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 14 practice 4 for chapter 14 lesson 5
-- 1. Write a query to display information about all views that you own
-- 2. Drop view emp_svu, emp_vu, emp_vu40
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------