--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 15 practice 1 for chapter 15 lesson 1
-- 1. Create a sequence called dept_seq that can be used with the PRIMARY KEY column of
-- the dept_new table. The sequence should start at 100 and have a maximum value of
-- 1,000. Have your sequence increment by 5, no cache and no cycle
-- 2. Create a sequence called test_seq with start value 10, increment by -2 minvalue 0 and
-- max value 20, with no cache and nocycle
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 15 practice 2 for chapter 15 lesson 2
-- 1. Use dept_seq to insert three new records in dept_new table
-- 2. Query the last generated sequence number of dept_seq sequence
-- 3. Use test_seq to generate numbers, what you observed?
-- 4. Modify test_seq and change it to cycle
-- 5. Use test_seq again to generate numbers, what you observed?
-- Chapter 15 practice 3 for chapter 15 lesson 3
-- 1. Write a query to display the following information about your sequences: sequence
-- name, increment value, minimum value, maximum value and last number, cycle flag.
-- 2. Drop sequence test_seq
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------