--------------------------------------------------------------------------------------------------------
--------------------------------- Managing Schema Objects
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- Chapter 18 practice 1 for chapter 18 lesson 1
-- 1. Create a table called my_dept with two columns dept_id number and dept_name
-- varchar2(200)
-- 2. Add PRIMARY KEY constraint called my_dept_id_pk to the my_dept table on the
-- dept_id column.
-- 3. Insert a record in the my_dept table as follows (1,’Marketing’)
-- 4. Insert a record in the my_dept table as follows (1,’HR’), what you observed?
-- 5. Check the constraint status from the dictionary views
-- 6. Disable the constraint my_dept_id_pk with validate option
-- 7. Try to perform a DML operation on my_dept table, what you observed?
-- 8. Check the constraint status from the dictionary views
-- 9. Disable the constraint my_dept_id_pk with novalidate option
-- 10. Insert a record in the my_dept table as follows (2,’HR’)
-- 11. Enable the constraint again and check the constraint status from the dictionary view,
-- what you observed?
-- 12. Add a unique key called dept_name_un on the dept_name column with deferrable
-- initially deferred option
-- 13. Insert a record (3,’HR’), what you observed?
-- 14. Try to commit the changes, what you observed?
-- 15. Drop dept_name_un constraint
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 18 practice 2 for chapter 18 lesson 2
-- 1. Create a temporary table called my_temp_items with three columns, item_id number(5),
-- item_name varchar2(50), item_description varchar2(100) using on commit preserve
-- rows
-- 2. Populate the table as below:
-- a) Insert two records in the temp table and commit the rows and query the table
-- b) open a new session a query the table, what you observed?
-- c) Insert a new record from the second session and commit the changes, query the
-- table from the first session? What you observed?
-- d) Exit from the first session and connect again and query the table, what you
-- observed?
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 18 practice 3 for chapter 18 lesson 3
-- 1. Let us assume you have a comma separated file contains customers information
-- (customer ID, customer name, email), and you want to load all the data in this file to the
-- database, create an external table to do achieve that