SELECT C.CAMPUS  || '-' || C.SUBJECT || '-' || C.CATALOG_NBR || '-' || C.SSR_COMPONENT || '-' || C.CLASS_NBR  AS CAMPUS_MATERIA_CATALOG
,CCA.DESCR AS MATERIA 
,C.STRM
,PERS.NAME
,PERS.EMPLID 
,TO_CHAR(CAST((CMP.MEETING_TIME_START) AS TIMESTAMP),'HH24:MI') || '-' || TO_CHAR(CAST((CMP.MEETING_TIME_END) AS TIMESTAMP),'HH24:MI') || '-' ||
CASE WHEN MON = 'Y' THEN 'L' END  || '' ||
CASE WHEN TUES = 'Y' THEN 'Ma' END  || '' ||
CASE WHEN WED = 'Y' THEN 'Mi' END || '' ||
CASE WHEN THURS = 'Y' THEN 'J' END || '' ||
CASE WHEN FRI = 'Y' THEN 'F' END || '' ||
CASE WHEN SAT = 'Y' THEN 'S' END || '' ||
CASE WHEN SUN = 'Y' THEN 'D' END  || '-' || CMP.FACILITY_ID AS DIA_DE_CLASES
FROM PS_CLASS_TBL C  
LEFT JOIN PS_CRSE_CATALOG CCA ON C.CRSE_ID=CCA.CRSE_ID
LEFT JOIN PS_CLASS_INSTR CIN ON C.CRSE_ID = CIN.CRSE_ID
AND C.CRSE_OFFER_NBR=CIN.CRSE_OFFER_NBR
AND C.STRM=CIN.STRM
AND C.SESSION_CODE=CIN.SESSION_CODE
AND C.CLASS_SECTION=CIN.CLASS_SECTION
LEFT JOIN PS_PERSONAL_DATA PERS ON CIN.EMPLID=PERS.EMPLID
LEFT JOIN PS_CLASS_MTG_PAT CMP ON C.CRSE_ID=CMP.CRSE_ID
AND C.CRSE_OFFER_NBR=CMP.CRSE_OFFER_NBR
AND C.STRM=CMP.STRM
AND C.SESSION_CODE=CMP.SESSION_CODE
AND C.CLASS_SECTION=CMP.CLASS_SECTION
WHERE CIN.EMPLID='01000146' AND 
        ((CCA.EFFDT = 
        (SELECT MAX(CCA_ED.EFFDT) FROM PS_CRSE_CATALOG CCA_ED 
        WHERE CCA.CRSE_ID = CCA_ED.CRSE_ID 
          AND CCA_ED.EFFDT <= SYSDATE) 
          AND CCA.EFFDT IS NOT NULL)
          OR CCA.EFFDT IS NULL)  
          




--SELECT * FROM PS_ETIQ_LST_CLS_VW WHERE EMPLID= '01000146'


--SELECT * FROM DUAL WHERE DUMMY BETWEEN LIKE '%A' AND '%B'


































/*
SELECT C.CAMPUS || '-' || C.SUBJECT || '-' || C.CATALOG_NBR || '-' || C.SSR_COMPONENT || '-' || C.CLASS_NBR AS CAMPUS_MATERIA_CATALOG 
 ,SUB.DESCR AS MATERIA 
 ,C.STRM 
 ,PERS.NAME 
 ,PERS.EMPLID 
 ,TO_CHAR(CAST((CMP.MEETING_TIME_START) AS TIMESTAMP) 
 ,'HH24:MI') || '-' || TO_CHAR(CAST((CMP.MEETING_TIME_END) AS TIMESTAMP) 
 ,'HH24:MI') || '-' || CASE WHEN MON = 'Y' THEN 'L' END || '' || CASE WHEN TUES = 'Y' THEN 'Ma' END || '' || CASE WHEN WED = 'Y' THEN 'Mi' END || '' || CASE WHEN THURS = 'Y' THEN 'J' END || '' || CASE WHEN FRI = 'Y' THEN 'F' END || '' || CASE WHEN SAT = 'Y' THEN 'S' END || '' || CASE WHEN SUN = 'Y' THEN 'D' END || '-' || CMP.FACILITY_ID AS DIA_DE_CLASES 
  FROM PS_CLASS_TBL C LEFT JOIN PS_SUBJECT_TBL SUB ON C.INSTITUTION=SUB.INSTITUTION 
   AND C.SUBJECT=SUB.SUBJECT LEFT JOIN PS_CLASS_INSTR CIN ON C.CRSE_ID = CIN.CRSE_ID 
   AND C.CRSE_OFFER_NBR=CIN.CRSE_OFFER_NBR 
   AND C.STRM=CIN.STRM 
   AND C.SESSION_CODE=CIN.SESSION_CODE 
   AND C.CLASS_SECTION=CIN.CLASS_SECTION LEFT JOIN PS_PERSONAL_DATA PERS ON CIN.EMPLID=PERS.EMPLID LEFT JOIN PS_CLASS_MTG_PAT CMP ON C.CRSE_ID=CMP.CRSE_ID 
   AND C.CRSE_OFFER_NBR=CMP.CRSE_OFFER_NBR 
   AND C.STRM=CMP.STRM 
   AND C.SESSION_CODE=CMP.SESSION_CODE 
   AND C.CLASS_SECTION=CMP.CLASS_SECTION 
 WHERE (( SUB.EFFDT = ( 
 SELECT MAX(SUB_ED.EFFDT) 
  FROM PS_SUBJECT_TBL SUB_ED 
 WHERE SUB.INSTITUTION =SUB_ED.INSTITUTION 
   AND SUB.SUBJECT =SUB_ED.SUBJECT 
   AND SUB_ED.EFFDT <= SYSDATE) 
   AND SUB.EFFDT IS NOT NULL) 
    OR SUB.EFFDT IS NULL)  */