SELECT A.INSTITUTION,F.ACAD_ORG AS DEPARTAMENTO,A.EMPLID,
B.FIRST_NAME  || ' ' || SUBSTR(B.MIDDLE_NAME,INSTR(B.MIDDLE_NAME,' ',-1) +1,1) || '. ' || B.LAST_NAME || ' ' ||  SUBSTR(B.SECOND_LAST_NAME,INSTR(B.SECOND_LAST_NAME,' ',-1) +1,1) AS FULL_NAME,
A.ACAD_CAREER AS GRADO_ACADEMICO,A.ACAD_PROG AS CARRERA,
A.CAMPUS,D.DESCR AS INDICATOR_SERVICIO ,EE.DESCR AS MOTIVO_INDIC_SERVICIO
FROM PS_ACAD_PROG A
LEFT JOIN PS_PERSONAL_DATA B ON B.EMPLID=A.EMPLID
LEFT JOIN PS_SRVC_IND_DATA C ON C.EMPLID=A.EMPLID
LEFT JOIN PS_SRVC_IND_CD_TBL D ON D.INSTITUTION =C.INSTITUTION 
AND D.SRVC_IND_CD =C.SRVC_IND_CD
LEFT JOIN PS_SRVC_IN_RSN_TBL EE ON EE.INSTITUTION=C.INSTITUTION
AND EE.SRVC_IND_CD=C.SRVC_IND_CD
AND EE.SRVC_IND_REASON=C.SRVC_IND_REASON
LEFT JOIN PS_ACAD_PROG_TBL F ON F.ACAD_CAREER=A.ACAD_CAREER 
AND F.INSTITUTION=A.INSTITUTION
AND F.ACAD_PROG=A.ACAD_PROG
WHERE A.EMPLID='00000078'AND 
  ( ( A.EFFDT = 
        (SELECT MAX(A_ED.EFFDT) FROM PS_ACAD_PROG A_ED 
        WHERE A.EMPLID = A_ED.EMPLID 
          AND A.ACAD_CAREER = A_ED.ACAD_CAREER 
          AND A.STDNT_CAR_NBR = A_ED.STDNT_CAR_NBR 
          AND A_ED.EFFDT <= SYSDATE) 
    AND A.EFFSEQ = 
        (SELECT MAX(A_ES.EFFSEQ) FROM PS_ACAD_PROG A_ES 
        WHERE A.EMPLID = A_ES.EMPLID 
          AND A.ACAD_CAREER = A_ES.ACAD_CAREER 
          AND A.STDNT_CAR_NBR = A_ES.STDNT_CAR_NBR 
          AND A.EFFDT = A_ES.EFFDT) 
     AND D.EFFDT = 
        (SELECT MAX(D_ED.EFFDT) FROM PS_SRVC_IND_CD_TBL D_ED 
        WHERE D.INSTITUTION = D_ED.INSTITUTION 
          AND D.SRVC_IND_CD = D_ED.SRVC_IND_CD 
          AND D_ED.EFFDT <= SYSDATE) 
     AND EE.EFFDT = 
        (SELECT MAX(EE_ED.EFFDT) FROM PS_SRVC_IN_RSN_TBL EE_ED 
        WHERE EE.INSTITUTION = EE_ED.INSTITUTION 
          AND EE.SRVC_IND_CD = EE_ED.SRVC_IND_CD 
          AND EE_ED.EFFDT <= SYSDATE) 
     AND F.EFFDT = 
        (SELECT MAX(F_ED.EFFDT) FROM PS_ACAD_PROG_TBL F_ED 
        WHERE F.INSTITUTION = F_ED.INSTITUTION 
          AND F.ACAD_PROG = F_ED.ACAD_PROG 
          AND F_ED.EFFDT <= A.EFFDT) ))

                  
          
          
          SELECT * FROM PS_ESTUD_IMPEDMNTO
          
        -- SELECT * FROM  PS_PERSONAL_DATA WHERE EMPLID='01148193'
         
         --SELECT FIRST_NAME  || ' ' || SUBSTR(MIDDLE_NAME,INSTR(MIDDLE_NAME,' ',-1) +1,1) || '. ' || LAST_NAME || ' ' ||  SUBSTR(SECOND_LAST_NAME,INSTR(SECOND_LAST_NAME,' ',-1) +1,1) 
         --AS NAME FROM  PS_PERSONAL_DATA WHERE EMPLID= '01148193'
          
       
        --SELECT  SUBSTR(SECOND_LAST_NAME,INSTR(SECOND_LAST_NAME,' ',-1) +1,1) FROM  PS_PERSONAL_DATA WHERE EMPLID= '01148193'



























--SELECT  SD.SRVC_IND_CD, SCT.DESCR,SIT.DESCR
--FROM PS_SRVC_IND_DATA SD
--LEFT JOIN PS_SRVC_IND_CD_TBL SCT ON SCT.INSTITUTION =SD.INSTITUTION 
--AND SCT.SRVC_IND_CD =SD.SRVC_IND_CD
--LEFT JOIN PS_SRVC_IN_RSN_TBL SIT ON SIT.INSTITUTION=SD.INSTITUTION
--AND SIT.SRVC_IND_CD=SD.SRVC_IND_CD
--AND SIT.SRVC_IND_REASON=SD.SRVC_IND_REASON


--LEFT JOIN PS_STDNT_CAREER SC ON P.EMPLID=SC.EMPLID  

--SELECT * FROM PS_ACAD_PROG
--
--SELECT * FROM PS_SRVC_IND_DATA
--
--SELECT * FROM PS_SRVC_IND_CD_TBL
--
--SELECT * FROM PS_SRVC_IN_RSN_TBL  