SELECT   A.INSTITUTION,B.CAMPUS,A.ACAD_CAREER,A.STRM, C.ACAD_ORG, A.ACAD_PROG,C.DESCR AS CARRERA 
,COUNT(*) AS TOTAL
FROM PS_STDNT_ENRL A
LEFT JOIN PS_ACAD_PROG B ON A.EMPLID = B.EMPLID 
AND A.ACAD_CAREER= B.ACAD_CAREER
AND A.INSTITUTION  = B.INSTITUTION
LEFT JOIN PS_ACAD_PROG_TBL C ON B.ACAD_CAREER = C.ACAD_CAREER 
AND C.INSTITUTION = B.INSTITUTION
AND C.ACAD_PROG = B.ACAD_PROG
WHERE A.STRM= '9905' AND
  ( B.EFFDT = 
        (SELECT MAX(B_ED.EFFDT) FROM PS_ACAD_PROG B_ED 
        WHERE B.EMPLID = B_ED.EMPLID 
          AND B.ACAD_CAREER = B_ED.ACAD_CAREER 
          AND B.STDNT_CAR_NBR = B_ED.STDNT_CAR_NBR 
          AND B_ED.EFFDT <= SYSDATE) 
    AND B.EFFSEQ = 
        (SELECT MAX(B_ES.EFFSEQ) FROM PS_ACAD_PROG B_ES 
        WHERE B.EMPLID = B_ES.EMPLID 
          AND B.ACAD_CAREER = B_ES.ACAD_CAREER 
          AND B.STDNT_CAR_NBR = B_ES.STDNT_CAR_NBR 
          AND B.EFFDT = B_ES.EFFDT)
    AND C.EFFDT = 
        (SELECT MAX(C_ED.EFFDT) FROM PS_ACAD_PROG_TBL C_ED 
        WHERE C.INSTITUTION = C_ED.INSTITUTION 
          AND C.ACAD_PROG = C_ED.ACAD_PROG 
          AND C_ED.EFFDT <= B.EFFDT))
GROUP BY  A.INSTITUTION, B.CAMPUS,A.ACAD_CAREER, A.STRM, C.ACAD_ORG, A.ACAD_PROG,C.DESCR 






--SELECT * FROM PS_ESTUD_INSCR_CAR   WHERE STRM='9905'


--SELECT * FROM PS_STDNT_ENRL


--select ACAD_ORG from PS_ACAD_PROG_TBL  WHERE ACAD_ORG <> ' '     
--
--UPDATE PS_ACAD_PROG_TBL SET ACAD_ORG='IIS'
--WHERE ACAD_PROG LIKE 'E%' 
--
--count almuno por dept / campus
--
--link con acad_prog para tener el campus

