SELECT  A.INSTITUTION,A.CAMPUS,A.ACAD_CAREER, B.STRM ,A.ACAD_PROG AS CARRERA,
C.DESCR,A.EMPLID,D.NAME,B.STDNT_ENRL_STATUS ,E.SSR_COMB_CUR_GPA as INDICE_CICLO,E.CUM_GPA AS INDICE_ACUMULADO
FROM PS_ACAD_PROG A
JOIN PS_STDNT_ENRL B ON B.EMPLID= A.EMPLID 
AND B.STDNT_ENRL_STATUS <> 'E'
AND A.ACAD_CAREER = B.ACAD_CAREER
AND A.INSTITUTION = B.INSTITUTION
JOIN PS_ACAD_PROG_TBL C ON C.ACAD_CAREER=A.ACAD_CAREER 
AND C.INSTITUTION=A.INSTITUTION
AND C.ACAD_PROG=A.ACAD_PROG
JOIN PS_NAMES_VW D ON A.EMPLID= D.EMPLID

JOIN PS_STDNT_CAR_TERM E ON E.EMPLID= B.EMPLID
AND E.ACAD_CAREER = B.ACAD_CAREER
AND E.INSTITUTION = B.INSTITUTION
AND E.STRM = B.STRM
--************************************
--JOIN PS_STDNT_CAR_TERM E ON E.EMPLID = A.EMPLID
--AND E.ACAD_CAREER= A.ACAD_CAREER
--AND E.STDNT_CAR_NBR = A.STDNT_CAR_NBR
--AND E.INSTITUTION = A.INSTITUTION

--JOIN PS_SSR_REGFORM F ON F.EMPLID= B.EMPLID
--AND F.ACAD_CAREER  = B.ACAD_CAREER 
--AND F.INSTITUTION = B.INSTITUTION
--AND F.STRM= B.STRM
--AND F.CLASS_NBR = B.CLASS_NBR
--WHERE B.STRM ='00000078' AND
--************************************
--JOIN PS_SSR_REGFORM F ON F.EMPLID= A.EMPLID
--AND F.ACAD_CAREER  = A.ACAD_CAREER 
--AND F.INSTITUTION = A.INSTITUTION

--AND F.STRM= A.STRM
--AND F.CLASS_NBR = A.CLASS_NBR
--WHERE B.EMPLID ='00000078' AND
--************************************
 WHERE  ( A.EFFDT = 
        (SELECT MAX(A_ED.EFFDT) FROM PS_ACAD_PROG A_ED 
        WHERE A.EMPLID = A_ED.EMPLID 
          AND A.ACAD_CAREER = A_ED.ACAD_CAREER 
          AND A.STDNT_CAR_NBR = A_ED.STDNT_CAR_NBR 
          AND A_ED.EFFDT <= SYSDATE) 
    AND A.EFFSEQ = 
        (SELECT MAX(A_ES.EFFSEQ) FROM PS_ACAD_PROG A_ES 
        WHERE A.EMPLID = A_ES.EMPLID 
          AND A.ACAD_CAREER = A_ES.ACAD_CAREER 
          AND A.STDNT_CAR_NBR = A_ES.STDNT_CAR_NBR 
          AND A.EFFDT = A_ES.EFFDT))
         
          

  


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  --select * from  ps_STDNT_CAR_TERM   --_SSR_COMB_CUR_GPA$0  --PARA INDICE DEL CICLO(PERIODO)

 --STDNT_CAR_TERM_CUM_GPA$0

SELECT * FROM PS_SSR_REGFORM

SELECT * FROM PS_ACAD_STDNG_ACTN         --_ACAD_STNDNG_ACTN$0


--**********************************************************--

SELECT * FROM PS_ACAD_PROG ORDER BY EMPLID DESC

SELECT STRM FROM PS_STDNT_CAR_TERM                    --_STRM$0

STRM (PS_CLASS_TBL,PS_STDNT_ENRL)

SELECT * FROM PS_STDNT_ENRL WHERE STDNT_ENRL_STATUS <> 'E'   --WHERE EMPLID='01148184' 