SELECT CATALOG_NBR,SUBJECT FROM PS_CLASS_TBL  WHERE SUBJECT = 'A-E'    -- (NO EFFDT)

SELECT * FROM PS_CLASS_INSTR

SELECT * FROM PS_PERSONAL_DATA

CLASS_INSTR_EMPLID$0

SELECT * FROM PS_CLASS_TBL  

SELECT * FROM PS_SUBJECT_TBL      --DESCR

SELECT * FROM PS_CLASS_MTG_PAT                                    --_MON$0


CASE
WHEN MON = 'Y' THEN 'L'
WHEN TUES = 'Y' THEN 'Ma'
WHEN WED = 'Y' THEN 'Mi'
WHEN THURS = 'Y' THEN 'J'
WHEN FRI = 'Y' THEN 'F'
WHEN SAT = 'Y' THEN 'S'
WHEN SUN = 'Y' THEN 'D'
ELSE  'N'
END AS DIA_DE_CLASES


CASE WHEN MON = 'Y' THEN 'L' END  || '' ||
CASE WHEN TUES = 'Y' THEN 'Ma' END  || '' ||
CASE WHEN WED = 'Y' THEN 'Mi' END || '' ||
CASE WHEN THURS = 'Y' THEN 'J' END || '' ||
CASE WHEN FRI = 'Y' THEN 'F' END || '' ||
CASE WHEN SAT = 'Y' THEN 'S' END || '' ||
CASE WHEN SUN = 'Y' THEN 'D' END AS DIA_DE_CLASES

    
SELECT TO_CHAR(CAST((A.MEETING_TIME_START) AS TIMESTAMP),'HH24.MI.SS.FF') 
  FROM PS_CLASS_MTG_PAT A

SELECT TO_CHAR(CAST((A.MEETING_TIME_START) AS TIMESTAMP),'HH24:MI') 
  FROM PS_CLASS_MTG_PAT A

SELECT TO_CHAR(MEETING_TIME_START) FROM PS_CLASS_MTG_PAT

TO_CHAR(EM.MEETING_DT, 'DD/') || TRIM (TO_CHAR(EM.MEETING_DT, 'Month', 'NLS_DATE_LANGUAGE = SPANISH')) || TO_CHAR(EM.MEETING_DT, '/YYYY' ) AS FECHA_EXAMEN,

                                                              /*PARA EL FILTER DE CATALOG_NBR*/ 
SELECT A.CAMPUS, A.SUBJECT, A.CATALOG_NBR, A.SSR_COMPONENT, A.CLASS_NBR, D.NAME, TO_CHAR(CAST((E.MEETING_TIME_START) AS TIMESTAMP),'HH24.MI.SS.FF') as time_start, 
TO_CHAR(CAST((E.MEETING_TIME_END) AS TIMESTAMP),'HH24.MI.SS.FF') time_end, CASE WHEN MON = 'Y' THEN 'L' END  || '' || 
CASE WHEN TUES = 'Y' THEN 'Ma' END  || '' || 
CASE WHEN WED = 'Y' THEN 'Mi' END || '' || 
CASE WHEN THURS = 'Y' THEN 'J' END || '' || 
CASE WHEN FRI = 'Y' THEN 'F' END || '' || 
CASE WHEN SAT = 'Y' THEN 'S' END || '' || 
CASE WHEN SUN = 'Y' THEN 'D' END dias_clases, E.FACILITY_ID, A.CRSE_ID, A.STRM, A.CLASS_SECTION, A.INSTITUTION, A.ACAD_GROUP, C.EMPLID, A.ACAD_CAREER, B.DESCR,B.CRSE_ID,TO_CHAR(B.EFFDT,'YYYY-MM-DD') 
  FROM ((((PS_CLASS_TBL A LEFT OUTER JOIN  PS_CLASS_INSTR C ON  A.CRSE_ID = C.CRSE_ID AND A.CRSE_OFFER_NBR = C.CRSE_OFFER_NBR AND A.STRM = C.STRM 
  AND A.SESSION_CODE = C.SESSION_CODE AND A.CLASS_SECTION = C.CLASS_SECTION ) LEFT OUTER JOIN  (PS_PERSONAL_DATA D INNER JOIN PS_PERALL_SEC_QRY D1 
  ON (D.EMPLID = D1.EMPLID AND  D1.OPRID = 'JURENA' )) ON  D.EMPLID = C.EMPLID ) LEFT OUTER JOIN  PS_CLASS_MTG_PAT E 
  ON  A.CRSE_ID = E.CRSE_ID AND A.CRSE_OFFER_NBR = E.CRSE_OFFER_NBR AND A.STRM = E.STRM AND A.SESSION_CODE = E.SESSION_CODE AND A.CLASS_SECTION = E.CLASS_SECTION ) 
  LEFT OUTER JOIN  PS_CRSE_CATALOG B ON  A.CRSE_ID = B.CRSE_ID ) 
WHERE A.CATALOG_NBR BETWEEN CONCAT(' ','399 = CATALOG_NBR') AND  CONCAT(' ','410')
--WHERE A.CATALOG_NBR > ' 399' AND A.CATALOG_NBR < ' 499' 
--AND A.CRSE_ID='000000' AND 
  ( ( A.INSTITUTION = :1 
     AND A.ACAD_CAREER = :3  
     AND A.STRM = :4 
     AND A.CAMPUS = :2 
     AND B.EFFDT = 
        (SELECT MAX(B_ED.EFFDT) FROM PS_CRSE_CATALOG B_ED 
        WHERE B.CRSE_ID = B_ED.CRSE_ID 
          AND B_ED.EFFDT <= SYSDATE) ))