INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2154,	10,	'Y', 	2,	0200, 	'BXE', 'P1', 	1,	'All Good');
INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2229,	10,	'Y', 	2,	0200, 	'BXE', 'P1', 	1,	'All Good');
INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2229,	15,	'N', 	1,	0060, 	'BAB', 'P1', 	0,	'NULL');
INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2496,	6, 'Y',  1,	1503,   'CYF', 'P2', 	2,	'All Good');
INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2903,	2, 'N', 	0,	0400, 	'P3',  'p2',  1,  'No muy bueno');
INSERT INTO PS_PSU_STU_SUG_EM (STUDENT_ID,	NUMBER,	IMPLEM_JT,	SUGG_CAT_JT,	COURSE_EM,	INSTRUCTOR_JT,	AWARD_EM,	SIZE_JT,	SUGGESTION_EM) 
VALUES
(2500,	2, 'Y',  1,	0410,   'ALL', 'P2', 	2,	'Instructor should talk a little slower');
