--------------------------------------------------------------------------------------------------------
--------------------------------- Indexes
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- Chapter 17 practice 1 for chapter 17 lesson 1
-- 1. Create a non unique index called emp_name_idx on the emp_name in the emp_new
-- table
-- 2. Create a non unique index called dept_id_idx on the dept_id in the emp_new table
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------
-- Chapter 17 practice 2 for chapter 17 lesson 2
-- 1. Write a query to display the table name, index name, column name, index type,
-- uniqueness flag of all indexes you own, filter the output for table name emp_new
-- 2. Drop emp_name_idx and dept_id_idx indexes
--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------